---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: internal-router
spec:
  endpoints:
  - dnsName: internal.thsp.dev
    recordTTL: 180
    recordType: A
    targets:
    - 192.168.25.4
