image:
  tag: v0.105.2

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: kong
    kubernetes.io/tls-acme: 'true'
    cert-manager.io/cluster-issuer: cert-manager
  hosts:
  - dns.thsp.dev
  tls:
  - secretName: pihole
    hosts:
    - dns.thsp.dev

serviceUDP:
  enabled: true
  type: LoadBalancer
  loadBalancerIP: '192.168.1.18'
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: adguard

# serviceDNSOverTLS:
#   enabled: true
#   type: LoadBalancer
#   loadBalancerIP: '192.168.1.18'
#   annotations:
#     metallb.universe.tf/address-pool: default
#     metallb.universe.tf/allow-shared-ip: adguard

persistence:
  config:
    enabled: true
    storageClass: openebs-hostpath
    size: 500Mi

serviceMonitor:
  enabled: true
