---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespace
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: infrastructure
  source:
    path: argocd/cluster01/infra/namespace
    repoURL: https://github.com/thspinto/rpi-cluster.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
