apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-config
  namespace: kong
data:
  nginx-custom.template: |
    events {}
    http {
      log_format main '$remote_addr - $remote_user [$time_local] "$request" '
      '$status $body_bytes_sent "$http_referer" '
      '"$http_user_agent" "$http_x_forwarded_for"';
    }
