---
ingressController:
  installCRDs: false

clustertelemetry:
  enabled: true

ingressController:
  image:
    repository: ghcr.io/thspinto/kubernetes-ingress-controller # TODO: go back to official release after https://github.com/Kong/kubernetes-ingress-controller/pull/926
    tag: latest

image:
  repository: thspinto/kong-arm64v8
  tag: latest

proxy:
  externalTrafficPolicy: Local
  stream:
    - containerPort: 9443
      servicePort: 9443
      parameters:
        - ssl

replicaCount: 2

env:
 nginx_http_log_format: >
  custom_fmt 'remote_addr=$remote_addr request="$request" host="$host"
  status=$status body_bytes_sent=$body_bytes_sent http_referer="$http_referer"
  http_user_agent="$http_user_agent" request_time=$request_time
  upstream_status=$upstream_status upstream_response_time=$upstream_response_time'
#  nginx_stream_log_format: |
#   custom_fmt '$remote_addr [$time_local] '
#   '$protocol $status $bytes_sent $bytes_received '
#   '$session_time'
#  proxy_access_log: /dev/stdout custom_fmt
