---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cillium
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: infrastructure
  source:
    path: argocd/infrastructure/cilium
    repoURL: https://github.com/thspinto/rpi-cluster.git
    targetRevision: HEAD
    helm:
      valuesFiles: values.yaml
  syncPolicy:
    automated:
      selfHeal: false
      prune: true
