---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: infrastructure
  source:
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: 2.4.1
    chart: loki-stack
    helm:
      values: |
        extraScrapeConfigs:
        - job_name: journal
          journal:
            path: /var/log/journal
            max_age: 12h
            labels:
              job: systemd-journal
          relabel_configs:
            - source_labels: ['__journal__systemd_unit']
              target_label: 'unit'
            - source_labels: ['__journal__hostname']
              target_label: 'hostname'
        extraVolumes:
          - name: journal
            hostPath:
              path: /var/log/journal
        extraVolumeMounts:
          - name: journal
            mountPath: /var/log/journal
            readOnly: true
  syncPolicy:
    automated:
      selfHeal: false
      prune: true
