---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: infrastructure
  source:
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: 2.4.1
    chart: loki-stack
    helm:
      values: |
        promtail:
          extraCommandlineArgs:
            - -client.external-labels=hostname=$(HOSTNAME)
          extraScrapeConfigs:
            - job_name: journal
              journal:
                path: /var/log/journal
                max_age: 12h
                labels:
                  job: systemd-journal
              relabel_configs:
                - source_labels: ['__journal__systemd_unit']
                  target_label: 'unit'
            - job_name: varlogs
              static_configs:
                - targets:
                    - localhost
                  labels:
                    job: varlogs
                    __path__: /var/log/*log
          pipelineStages:
            - match:
              selector: '{job="kong/kong-kong", container="proxy"}'
              stages:
              - regex:
                  expression: '^(?P<remote_addr>[\w\.]+) - (?P<remote_user>[^ ]*) \[(?P<time_local>.*)\] "(?P<method>[^ ]*) (?P<request>[^ ]*) (?P<protocol>[^ ]*)" (?P<status>[\d]+) (?P<body_bytes_sent>[\d]+) "(?P<http_referer>[^"]*)" "(?P<http_user_agent>[^"]*)"?'
              - labels:
                  #remote_addr:
                  #remote_user:
                  #time_local:
                  method:
                  #request:
                  #protocol:
                  status:
                  #body_bytes_sent:
                  #http_referer:
                  #http_user_agent:
          extraVolumes:
            - name: log
              hostPath:
                path: /var/log
            - name: journal
              hostPath:
                path: /var/log/journal
          extraVolumeMounts:
            - name: log
              mountPath: /var/log
              readOnly: true
            - name: journal
              mountPath: /var/log/journal
              readOnly: true
  syncPolicy:
    automated:
      selfHeal: false
      prune: true
