---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: infrastructure
  source:
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: 2.4.1
    chart: loki-stack
    helm:
      values: |
        promtail:
          extraScrapeConfigs:
            - job_name: system
              static_configs:
                - targets:
                    - localhost
                  labels:
                    host: ${HOSTNAME}
                    job: varlogs
                    __path__: /var/log/*log
          extraVolumes:
            - name: logs
              hostPath:
                path: /var/log/
          extraVolumeMounts:
            - name: logs
              mountPath: /var/log
              readOnly: true
  syncPolicy:
    automated:
      selfHeal: false
      prune: true
