---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: infrastructure
  source:
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: 2.4.1
    chart: loki-stack
    helm:
      values: |
        promtail:
          extraClientConfigs:
            hostname: ${HOSTNAME}
          extraScrapeConfigs:
            - job_name: journal
              journal:
                path: /var/log/journal
                max_age: 12h
                labels:
                  job: systemd-journal
              relabel_configs:
                - source_labels: ['__journal__systemd_unit']
                  target_label: 'unit'
            - job_name: system
              static_configs:
                - targets:
                    - localhost
                  labels:
                    job: varlogs
                    __path__: /var/log/*log
          extraVolumes:
            - name: log
              hostPath:
                path: /var/log
            - name: journal
              hostPath:
                path: /var/log/journal
          extraVolumeMounts:
            - name: log
              mountPath: /var/log
              readOnly: true
            - name: journal
              mountPath: /var/log/journal
              readOnly: true
  syncPolicy:
    automated:
      selfHeal: false
      prune: true
