---
hubble:
  listenAddress: ":4244"
  tls:
    auto:
      method: cronJob
  metrics:
    enabled:
    - dns:query;ignoreAAAA
    - drop
    - tcp
    - flow
    - icmp
    - http
  relay:
    enabled: true
  ui:
    enabled: true
    ingress:
      enabled: true
    annotations:
      kubernetes.io/ingress.class: kong
      konghq.com/plugins: private-service
      kubernetes.io/tls-acme: true
      cert-manager.io/cluster-issuer: cert-manager
    hosts:
    - hubble.thsp.dev
    tls:
    - secretName: hubble
      hosts:
      - hubble.thsp.dev
  serviceMonitor:
    enabled: true

localRedirectPolicy: true
nodeinit:
  restartPods: true
monitor:
  enabled: true
prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
#TODO: kubeProxyReplacement: "strict"
