---
hubble:
  listenAddress: ":4244"
  tls:
    auto:
      method: cronJob
  metrics:
    enabled:
    - dns:query;ignoreAAAA
    - drop
    - tcp
    - flow
    - icmp
    - http
  relay:
    enabled: true
  ui:
    enabled: true
localRedirectPolicy: true
nodeinit:
  restartPods: true
