image:
  tag: v5.7

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: kong
    kubernetes.io/tls-acme: 'true'
    cert-manager.io/cluster-issuer: cert-manager
  hosts:
  - dns.thsp.dev
  tls:
  - secretName: pihole
    hosts:
    - dns.thsp.dev

serviceDns:
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerIP: '192.168.1.18'
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: pihole-svc

persistentVolumeClaim:
  enabled: true
  size: 1Gi

admin:
  existingSecret: "pihole"
  passwordKey: "password"

doh:
  enabled: true

monitoring:
  podMonitor:
    enabled: true
  sidecar:
    enabled: true
