---
alertmanager:
  enabled: false

kube-state-metrics:
  image:
    repository: carlosedp/kube-state-metrics
    tag: v1.9.6

prometheus:
  prometheusSpec:
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    shards: null
  ingress:
    enabled: true
    annotations:
      konghq.com/plugins: private-service
      kubernetes.io/ingress.class: kong
      kubernetes.io/tls-acme: 'true'
      cert-manager.io/cluster-issuer: cert-manager
    hosts:
    - prometheus.thsp.dev
    tls:
    - secretName: cert-manager-prometheus
      hosts:
      - prometheus.thsp.dev

grafana:
  enabled: true
  ingress:
    enabled: true
    annotations:
      konghq.com/plugins: private-service
      kubernetes.io/ingress.class: kong
      kubernetes.io/tls-acme: 'true'
      cert-manager.io/cluster-issuer: cert-manager
    hosts:
    - grafana.thsp.dev
    tls:
    - secretName: cert-manager-grafana
      hosts:
      - grafana.thsp.dev

  envFromSecret: grafana-secret

  grafana.ini:
    paths:
      data: /var/lib/grafana/
      logs: /var/log/grafana
      plugins: /var/lib/grafana/plugins
      provisioning: /etc/grafana/provisioning
    analytics:
      check_for_updates: true
    log:
      mode: console
    grafana_net:
      url: https://grafana.net
    auth.generic_oauth:
        enabled: true
        allow_sign_up: false
        scopes: openid profile email
        auth_url: https://thsp-dev.us.auth0.com/authorize
        token_url: https://thsp-dev.us.auth0.com/oauth/token
        api_url: https://thsp-dev.us.auth0.com/userinfo
        client_id: NhA9Wba7M0nyACOJaErExhtT9Jr3jJfe
        client_secret:
