---
alertmanager:
  enabled: false

kube-state-metrics:
  image:
    repository: carlosedp/kube-state-metrics
    tag: v1.9.6

prometheus:
  prometheusSpec:
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
  ingress:
    enabled: true
    annotations:
      konghq.com/plugins: private-service
      kubernetes.io/ingress.class: kong
      kubernetes.io/tls-acme: 'true'
      cert-manager.io/cluster-issuer: cert-manager
    hosts:
    - prometheus.thsp.dev
    tls:
    - secretName: cert-manager-prometheus
      hosts:
      - prometheus.thsp.dev

grafana:
  enabled: true
  ingress:
    enabled: true
    annotations:
      konghq.com/plugins: private-service
      kubernetes.io/ingress.class: kong
      kubernetes.io/tls-acme: 'true'
      cert-manager.io/cluster-issuer: cert-manager
    hosts:
    - grafana.thsp.dev
    tls:
    - secretName: cert-manager-grafana
      hosts:
      - grafana.thsp.dev
