---
kind: TCPIngress
apiVersion: configuration.konghq.com/v1beta1
metadata:
  name: mqtt
  annotations:
    kubernetes.io/ingress.class: kong
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: "cert-manager"
spec:
  rules:
  - host: mqtt.thsp.dev
    port: 9443
    backend:
      serviceName: mosquitto
      servicePort: 1883
  tls:
    - hosts:
      - mqtt.thsp.dev
      secretName: mqtt-cert
