---
# Source: mosquitto/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  labels:
    helm.sh/chart: mosquitto-1.0.0
    app.kubernetes.io/name: mosquitto
    app.kubernetes.io/instance: mosquitto
    app.kubernetes.io/version: "2.0.7"
    app.kubernetes.io/managed-by: Helm
data:
  mosquitto.conf: |
    listener 1883
    allow_anonymous true
---
# Source: mosquitto/templates/common.yaml
apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  labels:
    helm.sh/chart: mosquitto-1.0.0
    app.kubernetes.io/name: mosquitto
    app.kubernetes.io/instance: mosquitto
    app.kubernetes.io/version: "2.0.7"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 1883
      targetPort: mqtt
      protocol: TCP
      name: mqtt
  selector:
    app.kubernetes.io/name: mosquitto
    app.kubernetes.io/instance: mosquitto
---
# Source: mosquitto/templates/common.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  labels:
    helm.sh/chart: mosquitto-1.0.0
    app.kubernetes.io/name: mosquitto
    app.kubernetes.io/instance: mosquitto
    app.kubernetes.io/version: "2.0.7"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: mosquitto
      app.kubernetes.io/instance: mosquitto
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mosquitto
        app.kubernetes.io/instance: mosquitto
    spec:
      
      serviceAccountName: default
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      containers:
      - name: mosquitto
        image: "eclipse-mosquitto:2.0"
        imagePullPolicy: IfNotPresent
        ports:
        - name: mqtt
          containerPort: 1883
          protocol: TCP
        volumeMounts:
        - mountPath: /mosquitto/config/mosquitto.conf
          name: mosquitto-config
          subPath: mosquitto.conf
        
        livenessProbe:
          tcpSocket:
            port: mqtt
          initialDelaySeconds: 0
          failureThreshold: 3
          timeoutSeconds: 1
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: mqtt
          initialDelaySeconds: 0
          failureThreshold: 3
          timeoutSeconds: 1
          periodSeconds: 10
        startupProbe:
          tcpSocket:
            port: mqtt
          initialDelaySeconds: 0
          failureThreshold: 30
          timeoutSeconds: 1
          periodSeconds: 5
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
      volumes:
      - configMap:
          name: mosquitto-config
        name: mosquitto-config
