---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hassio
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: home-assistant
    repoURL: https://k8s-at-home.com/charts/
    targetRevision: '11.0.4'
    helm:
      values: |
        prometheus:
          serviceMonitor:
            enabled: true

        persistence:
          config:
            enabled: true
            accessMode: ReadWriteOnce
            size: 1Gi

        ingress:
          main:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: kong
              kubernetes.io/tls-acme: 'true'
              cert-manager.io/cluster-issuer: cert-manager
              external-dns.alpha.kubernetes.io/hostname: ""
            hosts:
            - host: home.thsp.dev
              paths:
              - path: /
                pathType: Prefix
            tls:
            - secretName: home-assistant
              hosts:
              - home.thsp.dev

        http:
          server_host: 0.0.0.0
          ip_ban_enabled: true
          login_attempts_threshold: 5
          use_x_forwarded_for: true
          trusted_proxies:
          # Pod CIDR
          - 10.42.0.0/16

        image:
          tag: stable

  syncPolicy:
    automated:
      selfHeal: false
      prune: true
