---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hassio
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: kubedb
    repoURL: https://charts.appscode.com/stable/
    targetRevision: 'v2021.09.30'
    helm:
      values: |

  syncPolicy:
    automated:
      selfHeal: false
      prune: true
