---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubedb
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: kubedb
    repoURL: https://charts.appscode.com/stable/
    targetRevision: 'v2021.09.30'
    helm:
      values: |
        nodeSelector: {}
        catalog:
          elasticsearch: false
          etcd: false
          memcached: false
          mongodb: false
          mysql: false
          mariadb: true
          perconaxtradb: false
          pgbouncer: false
          postgres: true
          proxysql: false
          redis: true


  syncPolicy:
    automated:
      selfHeal: false
      prune: true
