roles:
- name: mikolak-net.raspi_config
  version: 1.2.3

- name: oefenweb.ufw
  version: v4.1.5

- name: xanmanning.k3s
  version: v2.8.0

- name: geerlingguy.swap
  version: 1.0.2

collections:
- name: community.kubernetes
  version: 1.2.0

- name: ansible.posix
  version: 1.2.0
